### ISSUE TITLE
Wrong transformation of  529 as isPartOf relation

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#102]
529 states the relation of a title to supplements, in the [MAB documentation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mabTitelBibliographischeDaten2001.txt;jsessionid=1203C36A7214E21CE07618A2FCB0B829.prod-worker3?__blob=publicationFile) it says:

```
529       TITEL VON FORTLAUFENDEN BEILAGEN

          Indikator:
          blank = verbale Beschreibung
          x     = reziproke Beziehung
          y     = nicht reziproke Beziehung
          z     = nicht differenzierte Beziehung
```

Thus, using hasPart would make more sense but doesn't seem quite right at all. Will look after the right property to use.

**Comment by dr0i** [comment]
Deployed to staging. Note:
1. test set is small and none of the above links work. Try: http://test.lobid.org/resource/HT000009600
2. If you follow the supplemental recoursively you will find only basic data. That is because the original resources are not part of the test set. See e.g. http://test.lobid.org/resource/HT006886479 . If you like, look up the productive data http://lobid.org/resource/HT006886479 and merge it virtually in your mind ;).  (Could be a todo to generate a more completely test set automatically).

**Comment by dr0i** [comment]
@acka47 now again ready to be reviewed

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
@acka47 have a look at the json context - is `hasSupplement` and `isSupplementOf` ok ?

**Comment by acka47** [comment]
See my comment at the commit: https://github.com/hbz/lobid/commit/357cb90227fe66515e3606baf487b4e6fc78e2e3#commitcomment-10210412

**Comment by dr0i** [comment]
Fixed. Pls have a look again.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Merged. Closing.
