### ISSUE TITLE
missing HTs

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#117]
http://lobid.org/resource/HT016371804 , http://okeanos-www.hbz-nrw.de/F/?func=find-c&ccl_term=IDN%3DHT016371804

http://lobid.org/resource/HT018449929 , http://okeanos-www.hbz-nrw.de/F/?func=find-c&ccl_term=IDN%3DHT018449929

**Comment by dr0i** [comment]
1. http://lobid.org/resource/HT016371804  does now (again) exist.  That's because the resource was updated not long ago (20150221) and was than ingested regularly. Your are right that it 'wasn't there in the first place, and I am still investigating this.
2. http://lobid.org/resource/HT018449929 still missing. Investigating.

**Comment by acka47** [comment]
http://lobid.org/resource/HT018449929 is there now. I guess we can close this, can't we @dr0i, @jschnasse?

**Comment by dr0i** [comment]
Everything fine, closing.
