### ISSUE TITLE
Remove statementOfResponsibility from author search

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#129]
The field `statementOfResponsibility` shouldn't be searched in an author query.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
@dr0i, bitte übernehmen Sie. I don't know what to do with these failing Travis tests.

**Comment by dr0i** [comment]
Fixed the code so that tests work as expected.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
@dr0i The search already worked as expected without adding the redundant property as workaround. Did you add it for the tests to work, then?

**Comment by dr0i** [comment]
Without the redundant property a query would take dct:creator into account. This would propably not lead to false hits, but let me say its plain wrong to do this. Furthermore, we have a template here that brings us awareneness of what happens behind the curtain: It's not that easy to change the queried properties (the code is also not easy to change, because it also affects the querying of the person endpoint!).

**Comment by acka47** [comment]
Thanks for the explanation. Everything looks good. +1 from my side.

**Comment by dr0i** [comment]
Deployed to production, closing.
