### ISSUE TITLE
No (mabxml) source found

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#228]
In the play logs there are many WARNing like this one:

```
2015-09-03 16:53:33,900 - [WARN] - from application in play-akka.actor.default-dispatcher-31 
No source data found for http://lobid.org/resource/HT013046158
```

While in fact the source is available, try the `source` tab in  http://lobid.org/resource/HT013046158 and also http://lobid.org/resource?id=HT013046158&format=source .

**Comment by fsteeg** [comment]
Hm, strange. I tried to reproduce this locally, but I don't get the message when I access HT013046158.

It also shouldn't be possible that the XML is both appended and the message is logged in the same request, see: https://github.com/hbz/lobid/blob/master/app/controllers/Application.java#L264

Maybe these messages are caused by separate requests that failed? Like a timeout or a non-200 response from the API at some point (these should be the two scenarios that could cause the message).

**Comment by dr0i** [comment]
Are these timeouts logged so that this assumption can be proved?
Would be good to have these logs in the play logs, can't find them now.
I looked again and the issue remains.

**Comment by fsteeg** [comment]
Opened #229 for improved logging.

**Comment by dr0i** [comment]
Improved logging  in lobid-staging doesn't show any http status codes.

**Comment by fsteeg** [comment]
Added status code, opened #230, deployed to staging.

**Comment by fsteeg** [comment]
Don't know what else to do, unassigning.

**Comment by dr0i** [comment]
Short status-quo:

> Maybe these messages are caused by separate requests that failed? Like a timeout or a non-200 response from the API at some point (these should be the two scenarios that could cause the message).

If the code you commited _is_ working, it must be another scenario.

**Comment by dr0i** [comment]
As this observation doesn't have _any_ effect we can savely ignore it officially by closing this issue. Sic!
