### ISSUE TITLE
Missing subjectChain parts

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid#274]
Reported by stakeholders, see point 7 at https://wiki1.hbz-nrw.de/pages/viewpage.action?pageId=58949642

Assigning to @acka47 for some details.

**Comment by acka47** [comment]
The issues with "Themensuche" are poorly documented by stakeholders. I am aware of the following issue:

Subject headings in subject chains aren't built according to `preferredName`s of the subjects involved and aren't seperated correctly. Examples:
- [BT000172095](http://lobid.org/nwbib/BT000172095): `Lüpke | Senner | Pferd | Pferdezucht` instead of `Lüpke | Senner, Pferd | Pferdezucht`
- [HT018627956](http://lobid.org/nwbib/HT018627956): `Einhardus | Vita Karoli Magni | Karl | Heiliges Römisches Reich, Kaiser | Liebesbeziehung | Nichteheliches Kind` instead of `Einhardus: Vita Karoli Magni | Karl, I., Heiliges Römisches Reich, Kaiser | Liebesbeziehung | Nichteheliches Kind` (note that also the `I.` is missing in the current subject chain)

I believe, that the biggest issues with subject chains would be solved if the actual pref labels would be used and seperators (`|`) would be inserted correctly.

(This wouldn't solve another problem, though, that we currently don't show subjects that don't have a GND ID under "Schlagwort", e.g. http://lobid.org/nwbib/HT018493481 where "Geschichte 1-700" can only be found in the "Schlagwortfolge".

**Comment by acka47** [comment]
Re. missing subject heading parts, this is _not_ only a problem for subject chains but for subjects in general, see https://github.com/lobid/lodmill/issues/766.

**Comment by acka47** [comment]
This will be resolved with https://github.com/hbz/lobid-resources/issues/29, thus is redundant. Closing.
