### ISSUE TITLE
Resources missing

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#305]
Reported by Publisso customer on 2016-04-26: 

> Die Titel vom 22.04. wurden beim nicht gefunden:
> 
> HT018950716
> HT018950768
> HT018950827
> HT018950840
> HT018951042
> HT018951067

**Comment by fsteeg** [comment]
API 1.x fixed via switch to yesterdays manual full index (see https://github.com/hbz/lobid/issues/304):

http://lobid.org/resource/HT018950716
http://lobid.org/resource/HT018950768
http://lobid.org/resource/HT018950827
http://lobid.org/resource/HT018950840
http://lobid.org/resource/HT018951042
http://lobid.org/resource/HT018951067

Sources still missing:

http://lobid.org/hbz01/HT018950716
http://lobid.org/hbz01/HT018950768
http://lobid.org/hbz01/HT018950827
http://lobid.org/hbz01/HT018950840
http://lobid.org/hbz01/HT018951042
http://lobid.org/hbz01/HT018951067

Data 2.0 still missing:

http://lobid.org/resources/HT018950716
http://lobid.org/resources/HT018950768
http://lobid.org/resources/HT018950827
http://lobid.org/resources/HT018950840
http://lobid.org/resources/HT018951042
http://lobid.org/resources/HT018951067

Ping @jschnasse for status.

**Comment by fsteeg** [comment]
Sources fixed:

http://lobid.org/hbz01/HT018950716
http://lobid.org/hbz01/HT018950768
http://lobid.org/hbz01/HT018950827
http://lobid.org/hbz01/HT018950840
http://lobid.org/hbz01/HT018951042
http://lobid.org/hbz01/HT018951067

**Comment by fsteeg** [comment]
Data 2.0 fixed:

http://lobid.org/resources/HT018950716
http://lobid.org/resources/HT018950768
http://lobid.org/resources/HT018950827
http://lobid.org/resources/HT018950840
http://lobid.org/resources/HT018951042
http://lobid.org/resources/HT018951067

It looks like this was a cascaded error caused by the failed full indexing (https://github.com/hbz/lobid/issues/304), on which the subsequent updates seem to depend (`tail -n 2000 weywot1:/var/mail/hduser` suggests this was caused by the missing `toBeUpdateFilesXmlClobs_afterBasedump.txt` after the failed full indexing).

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Closing.
