### ISSUE TITLE
HT019415170 can be found at http://lobid.org/resource/HT019415170 but not at http://lobid.org/resources/HT019415170

### ISSUE THREAD

**Issue by aquast** [hbz/lobid#351]
as fare as I can see both variants should be working
http://lobid.org/resource/HT019415170
http://lobid.org/resources/HT019415170

see:

http://lobid.org/resource/HT015374611
http://lobid.org/resources/HT015374611

Rquired for edoweb and frl

**Comment by fsteeg** [comment]
Looks like something went wrong when using the first new baseline for API 2 after the server migration.

Switched back to the previous index, and manually indexed updates since new baseline.

Fixed in production:

http://lobid.org/resource/HT019415170
http://lobid.org/resources/HT019415170

http://lobid.org/resource/HT015374611
http://lobid.org/resources/HT015374611

Leaving open for review by @dr0i next week.

**Comment by aquast** [comment]
thanx

**Comment by dr0i** [comment]
See https://github.com/hbz/lobid-resources/issues/541#issuecomment-323760245, and:

The API1.0 worked because the index wasn't switched thus only used an old (but daily updated) index.

Thus:
I switched the index for API2.0 back to the old fulldump base , just to be sure.

Todo:
check next monday if the script (getting the fulldump out of aleph; publish correctly AND update the alias for the internal index workflow) runs OK again.

**Comment by dr0i** [comment]
Checked. It's running fine again. Closing.
