### ISSUE TITLE
Publish usage guidelines

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#464]
There are lots of lobid API users, some of them quite heavy and several of them not giving credit to lobid as data source. It would make sense to create an API user guide with respect to the following questions (and probably more): 

- How to query lobid? What queries make sense for which use case (e.g. downloading dumps, single requests, getting updated files only)?
- How to give credit in your application/dataset to lobid as data source?

**Comment by hauschke** [comment]
Suggestion: Include a CITATION.cff for https://doi.org/10.11588/ip.2019.1.52673. 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by acka47** [comment]
By now, we have – thanks to @sebastian-meyer et al – a usage policy addressing different aspects, see https://pad.gwdg.de/s/entwurf-lobid-usage-policy. We will have to think about how to integrate it into the lobid.org website.

**Comment by acka47** [comment]
This will probably have to be split into different issues as the four sections on general, technical, legal and feedback aspects won't be put onto one page.

**Comment by kaena83** [comment]
This might be an approach:

1. Make the new policy visible on lobid startpage (see mockup): https://lobid.org/
![grafik](https://github.com/hbz/lobid/assets/119848543/19e497f9-3615-4860-85cd-6b015609636f)

2. Repeat analogously on startpages of lobid services (resources, organisations, gnd)

4. Make policy visible in API documentation of each service at top of page:
![grafik](https://github.com/hbz/lobid/assets/119848543/7cfd3e10-5072-4054-94b5-2b4d581bed0f)

The usage policy could be published on GitHub, as already done with the Data Protection Declaration.

**Comment by kaena83** [comment]
If this is ok @acka47 I`ll write the tickets in each board respectively.

**Comment by acka47** [comment]
> The usage policy could be published on GitHub.

I'd like to see it as part of the webpage but this does not affect the other proposals. I like the approach but would leave out "neu" before "Nutzungs-Policy" so that it does not get strange after some months...

**Comment by kaena83** [comment]
Yes, makes sense.  Would "lobid verfügt über eine Nutzungs-Policy." be ok? Or do you have another idea?

Who is responsible for making the changes on the lobid pages (so that I can assign them)? I would then write tickets for

a) the start page (lobid)

- create new page for usage policy
- add it in menu below (see mockup)
- add hint in lobid page (see mockup)

b) lobid resources 

- add hint in start page of lobid resources (see mockup)
- add hint in documentation of web api (see mockup)

c) lobid organisations 

- add hint in start page of lobid organisations (see mockup)
- add hint in documentation of web api (see mockup)

d) lobid-gnd

- add hint in start page of lobid gnd (see mockup)
- add hint in documentation of web api (see mockup)

I will change the phrases accordingly, link to respective pages / draft of usage policy and write the wording out in the tickets so that it can be c/p.

Is this fine?

**Comment by kaena83** [comment]
"Gewährleistung" should not be included in the Usage Policy.

**Comment by kaena83** [comment]
So this is the final approach:

![lobidMockup](https://github.com/hbz/lobid/assets/119848543/67ad4ed2-1618-49ad-b570-056383774f58)

**Comment by kaena83** [comment]
This is the approach for the usage policy with regards to the web api´s:

![APIMockup](https://github.com/hbz/lobid/assets/119848543/2ae60e9d-9995-4bf1-aeff-afcce5b6c011)

**Comment by acka47** [comment]
This is done, see https://blog.lobid.org/2023/10/12/lobid-usage-policy.html . Closing
