### ISSUE TITLE
Return 404 not found for URIs with no RDF response

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#63]
Examples:
- ~~http://lobid.org/organisation/DE-Bm3-3~~
- http://lobid.org/resource/1234567

**Comment by fsteeg** [comment]
We don't have a clear separation between searches and getting single resources in the API 1.x code. Supporting 404 on getting single resources would require some major refactoring. Giving 404 on empty searches too seems wrong and would break current API. Since we're phasing out the 1.x API anyway, I suggest we leave it as it is in 1.x and implement it correctly for 2.0, as it already is for the beta organisations API: `curl l -v -L http://beta.lobid.org/organisations/DE`

**Comment by acka47** [comment]
+1 Should we close this one then?
